name: domain
description: Domain layer for Packup.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  copy_with_extension_gen: ^4.0.2

dev_dependencies:
  build_runner: ^2.0.0
  test: ^1.17.0
  copy_with_extension_gen: ^4.0.0